[phases.setup]
nixPkgs = ["libGL", "python310"]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python app.py"
